apiVersion: v1
kind: Pod
metadata:
  name: debug-es
  namespace: openshift-logging
spec:
  nodeName: <worker-name>
  containers:
  - name: ubi
    image: registry.access.redhat.com/ubi7/ubi
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']
    volumeMounts:
    - mountPath: /mnt
      name: elasticsearch-storage
  volumes:
  - name: elasticsearch-storage
    persistentVolumeClaim:
      claimName: <PVC name>