apiVersion: v1
kind: Pod
metadata:
  name: sriovpod1
  annotations:
    k8s.v1.cni.cncf.io/networks: dpdk@test2
spec:
  containers:
      - command:
          - /bin/bash
          - -c
          - sleep INF
        image: registry.redhat.io/openshift4/dpdk-base-rhel8
        imagePullPolicy: Always
        name: dpdk
        resources:
          limits:
            cpu: "16"
#            hugepages-1Gi: 8Gi
            memory: 2Gi
          requests:
            cpu: "16"
#            hugepages-1Gi: 8Gi
            memory: 2Gi
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
              - SYS_RESOURCE
              - NET_RAW
              - NET_ADMIN
          runAsUser: 0