apiVersion: v1
kind: Pod
metadata:
  name: rhel8
  labels:
    app: rhel8
spec:
  containers:
  - name: myapp-container
    image: registry.access.redhat.com/ubi8/ubi
    command: ['sh', '-c', 'echo The app is running! && sleep 36000000']
    securityContext:
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      runAsUser: 1000000
      seccompProfile:
        type: RuntimeDefault