apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: approved-apache
spec:
  lookupPolicy:
    local: false
  tags:
  - name: "2.4"
    from:
      kind: DockerImage
      name: bitnami/apache:2.4
    referencePolicy:
      type: Source