  apiVersion: v1alpha1
  kind: AgentConfig
  metadata:
    name: sno-cluster
#  rendezvousIP: 192.168.123.80
  hosts:
    - hostname: master-0
      interfaces:
        - name: eno1
          macAddress: 02:01:00:00:00:66
      rootDeviceHints:
        deviceName: /dev/vda
      networkConfig:
        interfaces:
          - name: eno1
            type: ethernet
            state: up
            mac-address: 02:01:00:00:00:66
            ipv4:
              enabled: true
              address:
                - ip: 192.168.123.80
                  prefix-length: 24
              dhcp: false
        dns-resolver:
          config:
            server:
              - 192.168.123.1
        routes:
          config:
            - destination: 0.0.0.0/0
              next-hop-address: 192.168.123.1
              next-hop-interface: eno1
              table-id: 254