static_network_config:
- interfaces:
  - name: bond0
    type: bond
    state: up
    ipv4:
      address:
      - ip: 192.168.123.16
        prefix-length: 24
      dhcp: false
      enabled: true
    link-aggregation:
      mode: active-backup
      options:
        miimon: '140'
      slaves:
      - enp1s0
      - enp2s0
  routes:
    config:
    - destination: 0.0.0.0/0
      next-hop-address: 192.168.123.1
      next-hop-interface: bond0
  dns-resolver:
    config:
      server:
        - 192.168.123.1
  mac_interface_map:
  - mac_address: 02:01:00:00:00:60
    logical_nic_name: enp1s0
  - mac_address: 02:01:00:00:00:70
    logical_nic_name: enp2s0
- interfaces:
  - name: bond0
    type: bond
    state: up
    ipv4:
      address:
      - ip: 192.168.123.17
        prefix-length: 24
      dhcp: false
      enabled: true
    link-aggregation:
      mode: active-backup
      options:
        miimon: '140'
      slaves:
      - enp1s0
      - enp2s0
  routes:
    config:
    - destination: 0.0.0.0/0
      next-hop-address: 192.168.123.1
      next-hop-interface: bond0
  dns-resolver:
    config:
      server:
        - 192.168.123.1
  mac_interface_map:
  - mac_address: 02:01:00:00:00:61
    logical_nic_name: enp1s0
  - mac_address: 02:01:00:00:00:71
    logical_nic_name: enp2s0
- interfaces:
  - name: bond0
    type: bond
    state: up
    ipv4:
      address:
      - ip: 192.168.123.18
        prefix-length: 24
      dhcp: false
      enabled: true
    link-aggregation:
      mode: active-backup
      options:
        miimon: '140'
      slaves:
      - enp1s0
      - enp2s0
  routes:
    config:
    - destination: 0.0.0.0/0
      next-hop-address: 192.168.123.1
      next-hop-interface: bond0
  dns-resolver:
    config:
      server:
        - 192.168.123.1
  mac_interface_map:
  - mac_address: 02:01:00:00:00:62
    logical_nic_name: enp1s0
  - mac_address: 02:01:00:00:00:72
    logical_nic_name: enp2s0
