apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: vote-trigger
spec:
  serviceAccountName: pipeline
  interceptors:
    - ref:
        name: "gitlab" # Need to change from github to gitlab
      params:
        - name: "secretRef"
          value:
            secretName: gitlab-secret
            secretKey: secretToken
        - name: "eventTypes"
          value: ["Push Hook"] # Need to change from ["push"] to ["Push Hook"]
  bindings:
    - ref: vote-app
  template:
    ref: vote-app
---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-secret
type: Opaque
stringData:
  secretToken: "1234567"
