apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: cs-memcached
  namespace: openshift-marketplace
spec:
  displayName: My Test
  publisher: Company
  sourceType: grpc
  image: quay.io/rhn_support_cchen/memcached-operator-catalog:v0.0.1
  updateStrategy:
    registryPoll:
      interval: 10m