- name: Create htpasswd file with defined users
  command: "htpasswd -bBc {{ playbook_dir }}/ocp4-htpasswd {{ item.username }} {{ item.password }}"
  loop: "{{ users }}"
  args:
    creates: "{{ playbook_dir }}/ocp4-htpasswd"