apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: ubi # has to match .spec.template.metadata.labels
  serviceName: "ubi"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: ubi # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 1000
      containers:
      - name: ubi
        image: registry.redhat.io/ubi7/ubi
        command: ['sh', '-c', 'echo The app is running! && sleep 360000']
        ports:
        - containerPort: 80
          name: web
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - 'echo aaa; trap : TERM INT; sleep infinity & wait'