---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: openshift-flask
    app.kubernetes.io/component: openshift-flask
    app.kubernetes.io/instance: openshift-flask
  name: openshift-flask
  namespace: test-cmb
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    deployment: openshift-flask
  sessionAffinity: None
  type: ClusterIP