apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-config
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/pods/openshift-authentication_oauth-openshift*/oauth-openshift/0.log
      pos_file /tmp/accesslog.pos
      time_format %Y-%m-%dT%H:%M:%S.%N%Z
      tag login
      format none
      read_from_head "true"
    </source>

    <filter login>
      @type grep
      regexp1 message Login
    </filter>

    <match **>
      @type stdout
    </match>