---
apiVersion: v1
kind: Pod
metadata:
  name: sriovpod1
  namespace: test-1
  annotations:
    k8s.v1.cni.cncf.io/networks: example-network
spec:
  containers:
  - name: appcntr1
    image: centos/tools
    imagePullPolicy: IfNotPresent
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 300000; done;" ]

---
apiVersion: v1
kind: Pod
metadata:
  name: sriovpod2
  namespace: test-1
  annotations:
    k8s.v1.cni.cncf.io/networks: example-network
spec:
  containers:
  - name: appcntr1
    image: centos/tools
    imagePullPolicy: IfNotPresent
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 300000; done;" ]