apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: mc-mmu-kernel-args
spec:
  config:
    ignition:
      version: 3.2.0
  kernelArguments:
  - intel_iommu=on
  - iommu=pt
