apiVersion: v1
data:
  fluentd.conf: |
    <source>
      @type tail
      path /var/applog/basic-app.log
      tag accesslog
    </source>

    <match accesslog>
      @type stdout
    </match>
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: test-fluent-sidecar