apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentbit-config
data:
  fluentbit.conf: |
    [SERVICE]
        Flush        1
        Daemon       Off
        Log_Level    info

    [INPUT]
        Name        tail
        Path        /var/applog/basic-app.log

    [OUTPUT]
        Name        file
        Match       *
        File        1
        Path        /proc/1/fd