apiVersion: v1
kind: Pod
metadata:
  name: rhel7
  labels:
    app: rhel7
spec:
  containers:
  - name: myapp-container
    image: registry.access.redhat.com/ubi7/ubi
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']
  volumes:
    - name: pv
      persistentVolumeClaim:
        claimName: pv-7
