apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: toolbox
  namespace: test-hpa
spec:
  maxReplicas: 7
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: toolbox
  targetCPUUtilizationPercentage: 75