apiVersion: v1
baseDomain: cchen.work
controlPlane:
  name: master
  platform:
    openstack:
      type: PnTAE.CPU_8_Memory_16384_Disk_50
      additionalSecurityGroupIDs:
      - 604df802-aa38-4cd2-a65d-9af8484f91b5
      rootVolume:
        size: 80
        type: ceph
  replicas: 3
compute:
- name: worker
  platform:
    openstack:
      type: PnTAE.CPU_4_Memory_8192_Disk_50
      additionalSecurityGroupIDs:
      - 604df802-aa38-4cd2-a65d-9af8484f91b5
      rootVolume:
        size: 80
        type: ceph
  replicas: 4
metadata:
  name: multi-osp
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 192.168.0.0/24
  serviceNetwork:
  - 172.30.0.0/16
  networkType: OVNKubernetes
platform:
  openstack:
    cloud: psi
    externalNetwork: provider_net_shared_3
    computeFlavor: PnTAE.CPU_4_Memory_8192_Disk_50
    apiFloatingIP: 10.0.111.112
    ingressFloatingIP: 10.0.109.186
fips: false
pullSecret: '{"auths": ...}'
sshKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDTPFzWldumzMj3l5AndYGxTyUQxUi1cdUTHsUnwjMfcZXHc3dH9G8y1HUkfs4g3+gwLX/FmGsVWz6/61Y/+RyPJg5wI8XyP0QEYCaJ8BDiJw3rlMwrbBdIYBDwvdaMn655IM7qYgQbaXNIYKVRgaRStA2DzZqKJkdkLRW0JxA2nrRhKTLqtGzQXMYh897Aur5lt1NgafZYZbBy66LozCxe3c22avYpY7f3Of8zinJo4ZXQufHa0jQcL+6j/TpP0PYkK4R2/7UqWHP9+NREr5iKqBm3H9Ddc7ZtroKV9AaIckVyZcC8s+RlaHjI2PuSl+OBU2FnSHZbfnehSIRFhLr4O8MHy1jw3Ki/eR+V/2kDHIDHIi+1d7TTwBZMjMjXn8lffFezYze67bV+dHe+DonbZGJqXqA8+df8A3jMcl5/GQ1l5giNu6xUvQU0exH4Y2YurF7wcTy0dYJ60kM40l6QbXzNC00NShd8s5ixo8sv3rqpEpUq/JWNuZ5QNoA0eik= cchen@Chens-MacBook-Pro.local