apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-deployment
  labels:
    app: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      containers:
      - name: server
        image: quay.io/rhn_support_cchen/ollama:latest
        command:
          - ollama
          - serve
        securityContext:
          runAsUser: 0
      - name: model
        image: quay.io/rhn_support_cchen/ollama:latest
        command:
          - /bin/sh
          - -c
          - >
            ollama run gemma:2b &&
            sleep infinity

---
# Need to manually associate the floating IP in the OSP web console
apiVersion: v1
kind: Service
metadata:
  name: ollama-service
spec:
  selector:
    app: ollama
  ports:
    - protocol: TCP
      port: 11434
      targetPort: 11434
  type: LoadBalancer
