apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauthclient-app
spec:
  replicas: 1 # Number of desired replicas (adjust as needed)
  selector:
    matchLabels:
      app: your-app
  template:
    metadata:
      labels:
        app: your-app
    spec:
      containers:
      - name: your-app-container
        image: quay.io/rhn_support_cchen/oauthclient-app:v1.1
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: your-app-service
spec:
  selector:
    app: your-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000 # The port your pods are listening on