apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: whereaboutsnetwork
spec:
  config: '{
      "cniVersion": "0.3.1",
      "name": "whereaboutsnetwork",
      "type": "macvlan",
      "master": "ens7",
      "mode": "bridge",
      "ipam": {
        "type": "whereabouts",
        "range": "192.0.2.192/27"
      }
    }'